# 
policy_path: "pre_train/isaacgym/Jun06_18/policy_1.pt"
xml_path: "xml/isaacgym/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [25, 25, 0, 25, 25, 0]
kds: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]


default_angles: [1.22, -1.92, 0.0, 1.22, -1.92, 0.0]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
pos_action_scale: 0.5
vel_action_scale: 10.0 
cmd_scale: [1.0, 1.0, 1.0]
num_actions: 6
num_obs: 30

cmd_init: [ 0.0, 0.0, 0.3]